server:
 port : 8081
#spring:
#  application:
#    name: "backend"
#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB
#
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${ISSUER_URL:http://localhost:9999/realms/test-realm}
